// apps/docs/src/routes/Dashboard.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { session, setSession } from "../lib/auth";
  import { api } from "../lib/api";

  let error = "";

  onMount(async () => {
    try {
      if (!$session) {
        setSession(await api.getProfile());
      }
    } catch (err) {
      error = err instanceof Error ? err.message : "Could not load profile";
    }
  });
</script>

<section class="panel stack">
  <p class="eyebrow">Protected area</p>
  <h2>Dashboard</h2>

  {#if error}
    <p class="muted">{error}</p>
  {:else if $session}
    <p><strong>User:</strong> {$session.user.name} ({$session.user.email})</p>
    <p><strong>Role:</strong> {$session.user.role}</p>
  {:else}
    <p class="muted">Loading...</p>
  {/if}
</section>

// apps/web/pages/dashboard.vue
<script setup lang="ts">
definePageMeta({
  middleware: ["auth"],
});

const { data: session, error } = await useFetch("/api/profile", {
  credentials: "include",
});
</script>

<template>
  <section class="stack">
    <div class="panel stack">
      <p class="eyebrow">Protected route</p>
      <h2>Dashboard</h2>
      <p class="muted">
        This page demonstrates Nuxt SSR data loading with a server route and cookie-based auth check.
      </p>
      <p v-if="error" class="muted">Could not load the current profile.</p>
      <template v-else-if="session">
        <p><strong>User:</strong> {{ session.user.name }} ({{ session.user.email }})</p>
        <p><strong>Role:</strong> {{ session.user.role }}</p>
      </template>
    </div>
  </section>
</template>
